# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimeline',
            name='slug',
            field=models.CharField(default='', max_length=255, verbose_name='Zaman Tüneli Linki'),
        ),
    ]
