# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 21:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiLanguagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'İngilizce')], max_length=2, verbose_name='Dil')),
                ('title', models.CharField(max_length=155, verbose_name='Başlık')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Metin')),
            ],
            options={
                'verbose_name_plural': 'Mesaj İçerikleri',
                'verbose_name': 'Mesaj İçeriği',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name_plural': 'Mesajlar',
                'verbose_name': 'Mesaj',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('displayed', 'Görüntülenme'), ('liked', 'Beğeni'), ('shared', 'Paylaşılma Sayısı')], default='displayed', max_length=8, verbose_name='Tür')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('created_at', models.DateField(auto_now_add=True, help_text='Bu sütun kendiliğinden oluşacağı için formda düzenleme dışı kalmalıdır.', verbose_name='Oluşturulma Tarihi')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='stream.Post', verbose_name='Mesaj')),
            ],
            options={
                'verbose_name_plural': 'İstatistikler',
                'verbose_name': 'İstatistik',
            },
        ),
        migrations.AddField(
            model_name='multilanguagepost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='stream.Post', verbose_name='Mesaj'),
        ),
        migrations.AlterUniqueTogether(
            name='multilanguagepost',
            unique_together=set([('language', 'post')]),
        ),
    ]
